### ISSUE TITLE
There might be a bug in the file a.out.h

### ISSUE THREAD

**Issue by GenieKits** [7shi/pe2aout#1]
In the structure "exec", I think the third byte should be "a_cpu" and the "a_flags" should be the fourth byte.

**Comment by 7shi** [comment]
This project is based on MINIX of 10 years ago. The header file is derived from MINIX at the time.

* <https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/R3.1.0/include/a.out.h>

Now MINIX is very different, incorporating the NetBSD implementation. 

* <https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/master/sys/sys/exec_aout.h>

```c
struct exec {
	u_long	a_midmag;	/* htonl(flags<<26 | mid<<16 | magic) */
	u_long	a_text;		/* text segment size */
	u_long	a_data;		/* initialized data size */
	u_long	a_bss;		/* uninitialized data size */
	u_long	a_syms;		/* symbol table size */
	u_long	a_entry;	/* entry point */
	u_long	a_trsize;	/* text relocation size */
	u_long	a_drsize;	/* data relocation size */
};
```

Your point is correct. But there are no plans to follow the current development of MINIX.
